updating the ci
HorizenOfficial/zendoo-sc-cryptolib pull request #50
Opened 2021-05-25 09:25 UTC by lander86

2021-05-25 10:31 UTC, cronicc requested changes

2021-05-25 10:31 UTC, cronicc commented on ci/setup_env.sh
> +        export CONTAINER_PUBLISH="yes"
```suggestion
        export CONTAINER_PUBLISH="true"
```

2021-05-25 12:26 UTC, cronicc approved these changes

2021-05-26 09:54 UTC, albertog78 approved these changes

2021-06-04 06:41 UTC, phoinic approved these changes

2021-06-24 08:01 UTC, DanieleDiBenedetto approved these changes

2021-06-24 08:01 UTC, merged