InMemoryLazySparseMerkleTree
HorizenOfficial/zendoo-sc-cryptolib pull request #70
Opened 2021-11-17 12:09 UTC by DanieleDiBenedetto

Draft until dependencies and code ginger-lib side is stabilized. But still complete and ready to be reviewed.

2021-11-17 15:28 UTC, i-Alex requested changes

2021-11-17 15:28 UTC, i-Alex commented on jni/src/main/java/com/horizen/merkletreenative/InMemoryLazySparseMerkleTree.java
> +    public FieldElement addLeaves(List<PositionLeaf> leaves){
Why we should return root?
I would expect to add leaves and return boolean if it was successful

2021-11-17 15:28 UTC, i-Alex commented on api/src/lib.rs
> +) -> jobject
Java part expect `void` as a result.
I think, we don't need to calculate the root as a last step. Only remove leafs if possible.

2021-11-19 08:59 UTC, i-Alex approved these changes
Perfect!

2021-11-19 14:17 UTC, Yousefatm999 commented
Good

2021-11-19 14:19 UTC, Yousefatm999 approved these changes

2021-11-25 15:14 UTC, albertog78 approved these changes

2021-11-26 15:18 UTC, i-Alex approved these changes

2022-02-03 10:48 UTC, albertog78 approved these changes

2022-02-04 12:25 UTC, merged